### PR TITLE
Fix reload on change

### PR DESCRIPTION
**Pull request by karpediemnow**
Fix reload settings

[https://github.com/devattic/ConfigCrypter/issues/5](Related Issue)

### CODE REVIEW

**Comment by codelovercc** [comment]
Hi, you did a great job! Please merge this PR, Thks.

**Comment by karpediemnow** [comment]
Thanks!

**Comment by karpediemnow** [comment]
Hi, I don't have permission to merge into master  :(

**Comment by codelovercc** [comment]
I'm using this Repo in my project, and implemented symmetric encryption, and some other features. I can't wait the authors to merge this PR, so I used your code to fix reload problem and committed it with this PR url in commit message. so GitHub auto Mentioned you in this PR :) Thank you! Thanks to the members of ConfigCrypter!

**Comment by karpediemnow** [comment]
> I'm using this Repo in my project, and implemented symmetric encryption, and some other features. I can't wait the authors to merge this PR, so I used your code to fix reload problem and committed it with this PR url in commit message. so GitHub auto Mentioned you in this PR :) Thank you! Thanks to the members of ConfigCrypter!

I did the same... I have implemented other features like create a self signed certificate, autodiscovery of encrypted keys, certificate loaders from other sources like  aws and azure...

Thanks to ConfigCrypter  members 😉

**Comment by codelovercc** [comment]
> > I'm using this Repo in my project, and implemented symmetric encryption, and some other features. I can't wait the authors to merge this PR, so I used your code to fix reload problem and committed it with this PR url in commit message. so GitHub auto Mentioned you in this PR :) Thank you! Thanks to the members of ConfigCrypter!
> 
> I did the same... I have implemented other features like create a self signed certificate, autodiscovery of encrypted keys, certificate loaders from other sources like aws and aws...
> 
> Thanks to ConfigCrypter members 😉
Hi, glad to hear that!
I'd like certificate loaders from web api over https, I have implemented that for symmetric encryption😀, encrypt keys when value of the keys have a specialized prefix, and encrypt/decrypt entire file and change the encryption secret key or certificate for the encrypted file are also implemented.

**Pull request closed without merging**
